[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements-prod.txt"]

[start]
cmd = "uvicorn api.main:app --host 0.0.0.0 --port $PORT"
